### PR TITLE
Fix complex parsing for minutes

### LINKED ISSUE #124: Translation with multiple commas not readable
Hello, I have an issue using your library when I'm facing complex cron expressions like :

`5-45/10,*/5,9 * * * *`

The human translation is not understandable.

**Expected** : Every 10 minutes from 5th minutes to 45th minute, every 5 minutes, at 9th minute
**Actual** : Every 10,* minutes, minutes 5 through 45 past the hour

Thank you for your time.

### PR DESCRIPTION
**Pull request by randallreedjr**
Fixes #124 

This is my first pass. Unfortunate, the requested wording was not compatible with established patterns in the library. 

- Requested: "Every 10 minutes from 5th minutes to 45th minute, every 5 minutes, at 9th minute"
- Actual: "Every 10 minutes, minutes 5 through 45 past the hour, every 5 minutes, at 9 minutes past the hour"

This was accomplished by splitting the expression on the comma and iteratively calling `getSegmentDescription` for each segment. So each segment is translated as it would be if it were the entire expression.

The downside to this approach is that "minutes 5 through 45 past the hour" is a little unclear. I am open to suggestions as to how to improve that (e.g. potentially joining the segments with semi-colons, "Every 10 minutes, minutes 5 through 45 past the hour; every 5 minutes; at 9 minutes past the hour")

---

This change also uncovered what I believe to be a mistake in a separate test, updated in a separate commit, for the expression `0 */4,6 * * *`.

Existing: "At 0 minutes past the hour, every 4,6 hours"
Updated: "At 0 minutes past the hour, every 4 hours, at 06:00 AM"

I believe the update is correct, based on the order of operations. This was confirmed by [crontab.guru](https://crontab.guru/#0_*/4,6_*_*_*).

### CODE REVIEW

**Comment by bradymholt** [comment]
Thanks for your contribution @randallreedjr.  I've been on vacation so my response has been a bit delayed.

Please see my comment [here](https://github.com/bradymholt/cRonstrue/issues/124#issuecomment-680960934).  I the fix here should be for each value (delimited by a commas) to stand on its own, and to not modify a prior value in the segment.

**Comment by randallreedjr** [comment]
@bradymholt Sorry, I'm a little confused. Isn't that what my change does? 
https://github.com/bradymholt/cRonstrue/pull/163/files#diff-466b9f6f59392736d5a0c440189df807R483

File: src/expressionDescriptor.ts [hunk 1]
```diff
@@ -461,7 +461,20 @@ export class ExpressionDescriptor {
       description = allDescription;
     } else if (!StringUtilities.containsAny(expression, ["/", "-", ","])) {
       description = StringUtilities.format(getDescriptionFormat(expression), getSingleItemDescription(expression));
-    } else if (expression.indexOf("/") > -1) {
+    } else if (expression.indexOf("/") > -1 && expression.indexOf(",") > -1) {
```
Comment (bradymholt) [inline src/expressionDescriptor.ts:464]: The if block on 492-494 (`if (betweenSegmentDescription.indexOf(", ")...`) can probably be removed now since it shouldn't be hit with this change.

File: test/cronstrue.ts [hunk 2]
```diff
@@ -460,7 +460,7 @@ describe("Cronstrue", function() {
     });
 
     it("0 */4,6 * * * ", function() {
-      assert.equal(construe.toString(this.test.title), "At 0 minutes past the hour, every 4,6 hours");
+      assert.equal(construe.toString(this.test.title), "At 0 minutes past the hour, every 4 hours, at 06:00 AM");
```
Comment (bradymholt) [inline test/cronstrue.ts:463]:
```suggestion
      assert.equal(construe.toString(this.test.title), "At 0 minutes past the hour, every 4 hours, and at 06:00 AM");
```

File: test/cronstrue.ts [hunk 3]
```diff
@@ -476,6 +476,13 @@ describe("Cronstrue", function() {
         "Every 3 minutes, minutes 0 through 20 past the hour, between 09:00 AM and 09:59 AM"
       );
     });
+
+    it("5-45/10,*/5,9 * * * *", function () {
+      assert.equal(
+        construe.toString(this.test.title),
+        "Every 10 minutes, minutes 5 through 45 past the hour, every 5 minutes, at 9 minutes past the hour"
```
Comment (bradymholt) [inline test/cronstrue.ts:483]:
```suggestion
        "Every 10 minutes, minutes 5 through 45 past the hour, every 5 minutes, and at 9 minutes past the hour"
```

File: src/expressionDescriptor.ts [hunk 4]
```diff
@@ -461,7 +461,20 @@ export class ExpressionDescriptor {
...
+      for (let i = 0; i < segments.length; i++) {
+        segmentDescriptions.push(this.getSegmentDescription(segments[i],
+          allDescription,
+          getSingleItemDescription,
+          getIntervalDescriptionFormat,
+          getBetweenDescriptionFormat,
+          getDescriptionFormat
+        ));
+      }
+      description = segmentDescriptions.join(", ");
```
Comment (bradymholt) [inline src/expressionDescriptor.ts:476]: Although I like your succinct approach with `.join`, the handling for `expression.indexOf(",") > -1 && expression.indexOf("/") == -1` starting on line 523 handles formatting of multiple values by prefixing last with ", and" and a few other things.  To keep it consistent I'm hoping we can use a similar approach.

Here is a suggested change:

```suggestion
      let segments: string[] = expression.split(",");
      let descriptionContent: string = "";
      for (let i = 0; i < segments.length; i++) {
        if (i > 0) {
          descriptionContent += ",";

          if (i < segments.length - 1) {
            descriptionContent += " ";
          }
        }

        if (i > 0 && segments.length > 1 && (i == segments.length - 1 || segments.length == 2)) {
          descriptionContent += `${this.i18n.spaceAnd()} `;
        }

        descriptionContent += this.getSegmentDescription(segments[i],
          allDescription,
          getSingleItemDescription,
          getIntervalDescriptionFormat,
          getBetweenDescriptionFormat,
          getDescriptionFormat
        );
      }

      description = descriptionContent;
```

**Comment by bradymholt** [comment]
@randallreedjr - I think I see where I was confused.  I saw "every 5 minutes, at 9 minutes past the hour" and thought the "at 9 minutes past the hour" part was modifying (qualifying) the prior value "every 5 minutes".  But, I do see how your change doesn't do what I thought it did.  But, I think adding a ", and" like "every 5 minutes, **and** at 9 minutes past the hour" could help clarify this.  I've added some comments.  Thanks!

File: src/expressionDescriptor.ts [hunk 5]
```diff
@@ -461,7 +461,20 @@ export class ExpressionDescriptor {
       description = allDescription;
     } else if (!StringUtilities.containsAny(expression, ["/", "-", ","])) {
       description = StringUtilities.format(getDescriptionFormat(expression), getSingleItemDescription(expression));
-    } else if (expression.indexOf("/") > -1) {
+    } else if (expression.indexOf("/") > -1 && expression.indexOf(",") > -1) {
+      let segments: string[] = expression.split(",");
+      let segmentDescriptions: string[] = [];
+      for (let i = 0; i < segments.length; i++) {
+        segmentDescriptions.push(this.getSegmentDescription(segments[i],
```
Comment (bradymholt) [inline src/expressionDescriptor.ts:468]: I like this recursive approach for handling multiple values in a segment delimited by a comma.  Once this PR is merged, I plan to circle back and do a bit of refactoring to use this approach in a few other places.

**Comment by bradymholt** [comment]
I'm going to go ahead and merge this in as is and the create a new PR with a few additional tweaks.  Thanks for the contribution @randallreedjr !

**Comment by randallreedjr** [comment]
Thanks Brady! Sorry I couldn't get to the rest of the changes. I'm happy to help out if you want to split up some of the remaining updates.
